language: generic 

sudo: required
services:
  - docker

before_install: 
  - docker build -t sbk888sbk/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true sbk888sbk/react-test npm test

after_success: 
  - docker build -t sbk888sbk/multi-client ./client
  - docker build -t sbk888sbk/multi-server ./server
  - docker build -t sbk888sbk/multi-worker ./worker
  - docker build -t sbk888sbk/multi-ngix ./ngix


